/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Areas */
        get: operations["list_areas_areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Postal */
        get: operations["resolve_postal_areas_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Categories
         * @description The category taxonomy; the app renders its own labels and icons from the ids.
         */
        get: operations["categories_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Detail */
        get: operations["event_detail_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + database connectivity. 200 when the DB answers, 503 otherwise.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppliedFilters
         * @description Echoed back so the app can show the filters as editable chips.
         */
        AppliedFilters: {
            /** Area */
            area: string | null;
            /** Categories */
            categories: string[];
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /** Free */
            free: boolean | null;
            /** Include Restricted */
            include_restricted: boolean;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Online */
            online: string;
            /** Radius Km */
            radius_km: number | null;
            /** Region */
            region: string | null;
            /** Sort */
            sort: string;
            /** When */
            when: string | null;
        };
        /** AreaOut */
        AreaOut: {
            /** Planning Area */
            planning_area: string;
            /** Region */
            region: string;
        };
        /** AskAppliedFilters */
        AskAppliedFilters: {
            /** Area */
            area: string | null;
            /** Categories */
            categories: string[];
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /** Free */
            free: boolean | null;
            /** Include Restricted */
            include_restricted: boolean;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Online */
            online: string;
            /** Place */
            place: string | null;
            /** Radius Km */
            radius_km: number | null;
            /** Region */
            region: string | null;
            /** Semantic Query */
            semantic_query: string;
        };
        /**
         * AskFilters
         * @description The app's filter chips. Anything set here overrides what the question implies.
         */
        AskFilters: {
            /** Area */
            area?: string | null;
            /** Categories */
            categories?: string[] | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Free */
            free?: boolean | null;
            /**
             * Include Restricted
             * @default false
             */
            include_restricted: boolean;
            /** Online */
            online?: ("include" | "exclude" | "only") | null;
            /** Radius Km */
            radius_km?: number | null;
            /** Region */
            region?: ("CENTRAL" | "EAST" | "NORTH" | "NORTH-EAST" | "WEST") | null;
            /** When */
            when?: ("today" | "weekend" | "week" | "month") | null;
        };
        /** AskRequest */
        AskRequest: {
            /**
             * @default {
             *       "include_restricted": false
             *     }
             */
            filters: components["schemas"]["AskFilters"];
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Q */
            q: string;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /**
             * Time Format
             * @default 24h
             * @enum {string}
             */
            time_format: "24h" | "12h";
            /**
             * Top K
             * @default 12
             */
            top_k: number;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer Text */
            answer_text: string;
            /**
             * Answered By
             * @enum {string}
             */
            answered_by: "claude" | "template";
            applied_filters: components["schemas"]["AskAppliedFilters"];
            /** Cited Event Ids */
            cited_event_ids: number[];
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Notes */
            notes: string[];
            /**
             * Parser
             * @enum {string}
             */
            parser: "llm" | "rules";
        };
        /** EventDetail */
        EventDetail: {
            /** All Day */
            all_day: boolean;
            /** Audience */
            audience: string;
            /** Categories */
            categories: string[];
            /** Confidence */
            confidence: string;
            /** Description */
            description: string | null;
            /** Distance M */
            distance_m: number | null;
            /** Ends At */
            ends_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Id */
            id: number;
            /** Image Url */
            image_url: string | null;
            /** Is Free */
            is_free: boolean | null;
            /** Is Online */
            is_online: boolean;
            /** Language */
            language: string[] | null;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            location: components["schemas"]["Location"] | null;
            /** Organizer */
            organizer: string | null;
            /** Price Max Sgd */
            price_max_sgd: number | null;
            /** Price Min Sgd */
            price_min_sgd: number | null;
            /** Registration Url */
            registration_url: string | null;
            /** Sessions */
            sessions: components["schemas"]["SessionOut"][];
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            /** Title Alt */
            title_alt: string | null;
            venue: components["schemas"]["VenueOut"] | null;
        };
        /** EventOut */
        EventOut: {
            /** All Day */
            all_day: boolean;
            /** Audience */
            audience: string;
            /** Categories */
            categories: string[];
            /** Confidence */
            confidence: string;
            /** Distance M */
            distance_m: number | null;
            /** Ends At */
            ends_at: string | null;
            /** Id */
            id: number;
            /** Image Url */
            image_url: string | null;
            /** Is Free */
            is_free: boolean | null;
            /** Is Online */
            is_online: boolean;
            location: components["schemas"]["Location"] | null;
            /** Organizer */
            organizer: string | null;
            /** Price Max Sgd */
            price_max_sgd: number | null;
            /** Price Min Sgd */
            price_min_sgd: number | null;
            /** Registration Url */
            registration_url: string | null;
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Status */
            status: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            venue: components["schemas"]["VenueOut"] | null;
        };
        /** EventsPage */
        EventsPage: {
            filters: components["schemas"]["AppliedFilters"];
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Limit */
            limit: number;
            /** Next Offset */
            next_offset: number | null;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Location */
        Location: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** SessionOut */
        SessionOut: {
            /** Ends At */
            ends_at: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** SourceOut */
        SourceOut: {
            /** Source Id */
            source_id: string;
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VenueOut */
        VenueOut: {
            /** Address */
            address: string | null;
            /** Name */
            name: string;
            /** Planning Area */
            planning_area: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Region */
            region: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_areas_areas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"][];
                };
            };
        };
    };
    resolve_postal_areas_resolve_get: {
        parameters: {
            query: {
                /** @description 6-digit Singapore postal code */
                postal: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    }[];
                };
            };
        };
    };
    list_events_events_get: {
        parameters: {
            query?: {
                /** @description Repeatable; matches any. See GET /categories. */
                category?: string[] | null;
                /** @description Preset window in SGT; excludes date_from/date_to. */
                when?: ("today" | "weekend" | "week" | "month") | null;
                /** @description ISO date (SGT day) or datetime. Default: now. */
                date_from?: string | null;
                /** @description Inclusive ISO date or datetime. Default: 30 days on. */
                date_to?: string | null;
                lat?: number | null;
                lng?: number | null;
                /** @description Used with lat/lng. */
                radius_km?: number;
                /** @description Planning area, e.g. SENGKANG ('events in'). */
                area?: string | null;
                /** @description CENTRAL, EAST, NORTH, NORTH-EAST or WEST. */
                region?: string | null;
                free?: boolean | null;
                /** @description Default: exclude when searching around a point, include otherwise. */
                online?: ("include" | "exclude" | "only") | null;
                /** @description Also show students/members/alumni-only events. */
                include_restricted?: boolean;
                /** @description Default: distance with lat/lng, soonest otherwise. */
                sort?: ("soonest" | "distance" | "blend") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_detail_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
